package eu.vdmr.util.gnuplot;

public enum GnuPlottingStyles {
    Boxerrorbars,
    Boxes,
    Boxplot,
    Boxxerror,
    Candlesticks,
    Circels,
    Ellipses,
    Dots,
    Fillescurves,
    Financebars,
    Fsteps,
    Fillsteps,
    Histeps,
    Histogram,
    Image,
    Impulses,
    Labels,
    Lines,
    Lisespoints,
    Parallelaxes,
    Points,
    Steps,
    Rgbalpha,
    Rgbimage,
    Vectors,
    Xerrorbars,
    Xyerrorbars,
    Yerrorbars,
    Xerrorlines,
    Yerrorlines,
    Zerrorfill
}
